services:
    app:
        build: .
        container_name: dur-property-valuations-app
        volumes:
            - .:/app
        ports:
            - "8000:8000" # Expose app port to host
        environment:
            - DATABASE_URL=postgres://postgres:password@db:5432/property-valuations
        depends_on:
            - db
        command: python server.py

    db:
        image: postgres:latest
        container_name: postgres-db
        environment:
            - POSTGRES_USER=${DB_USER:-postgres} # Default to 'postgres' if not in .env
            - POSTGRES_PASSWORD=${DB_PASSWORD:-password} # Default password
            - POSTGRES_DB=${DB_NAME:-property-valuations} # Default DB name
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 10s
            retries: 5
